### ISSUE TITLE
What happens if I await an eager token but it runs to completion before I attach the parent continuation?

### ISSUE THREAD

**Issue by npuichigo** [tankiJong/cpp-coroutine-job-system#1]
What happens if I await a eager token but it runs to completion before I attach the parent continuation?
```c++
template<typename Promise>
      bool await_suspend( std::coroutine_handle<Promise> awaitingCoroutine ) noexcept
      {
         return coroutine.promise().SetContinuation( awaitingCoroutine );
      }

template<typename Promise>
   bool SetContinuation(const std::coroutine_handle<Promise>& parent)
   {
      promise_base& parentPromise = parent.promise();

      auto expectedState = eOpState::Processing;
      bool updated = parentPromise.SetState( expectedState, eOpState::Suspended );
      ENSURES( updated || expectedState == eOpState::Suspended);

      mParent = parent;
      mScheduleParent = &ScheduleParentTyped<Promise>;
      return !mHasParent.exchange(true, std::memory_order_release);
   }


```

**Comment by tankiJong** [comment]
The timeline will be something like this:
- On "main" thread, parent execution
-- On "main" thread, encounter `co_await child_token;`(this task is already running, potentially completed)
--- On "some other" thread, Run `child_token_await_base::finial_suspend` related logic(invoke `ScheduleParent`), but we found no parent attached at the moment
--- On "main" thread, `child_token_await_base::await_suspend(parent_coroutine)`, **parent attached**

This means the parent will never be resumed. Thanks for catching the bug!

To fix it, we can check `coro_handle.done()` and return false for `await_suspend`, where we will not set parent but because `await_suspend` will return false, we will immediately resume parent coroutine in the current running context. One slightly tricky part is to make sure the operation is atomic so that we do not have another race condition.

If you would like, feel free to make a PR :)

**Comment by tankiJong** [comment]
I made a fix. As I am not a concurrency guru, please let me know if I missed anything else.

**Comment by npuichigo** [comment]
Thanks for your quick fix. I'll have a try.😀
